name: Update Deployment Image

on:
  push:
    branches:
      - main  # Se activa cuando hay un push a la rama main

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Git (para hacer commit y push)
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Paso 3: Actualizar la imagen en el deployment.yaml
      - name: Update Deployment Image
        run: |
          # Reemplaza la imagen en el deployment.yaml
          sed -i "s|image:.*|image: image-registry.openshift-image-registry.svc:5000/technical-assistant/technical-assistant-git:latest|g" deployment-technical-assistant-git.yaml

      # Paso 4: Hacer commit y push de los cambios
      - name: Commit and Push Changes
        run: |
          git add deployment-technical-assistant-git.yaml
          git commit -m "Update image to latest version"
          git push origin main