name: Update Deployment Image

on: #obligatorio para todos los workflows, indica que se activa cuando se hace un push a la rama main
  push:
    branches:
      - main  # Se activa cuando hay un push a la rama main

jobs: #indica los jobs que se van a ejecutar
  update-deployment: #nombre del job, puede ser cualquier nombre
    runs-on: ubuntu-latest  #indica que se va a ejecutar en un runner de ubuntu (se puede usar windows-latest, macos-latest) depende del sist operativo en el que estas trabajando.

    steps: #primer paso del jobs
      # Paso 1: Checkout del código
      - name: Checkout code #puede ser cualquier nombre
        uses: actions/checkout@v3 #uses:indica que este paso usa una acción de GitHub predefinida, actions/checkout: descarga el código fuente del repositorio,  @v3:indica que está usando la versión 3 de la acción.
        #Esto es lo mismo que hacer manualmente: git clone https://github.com/ldufaur/Technical-Assistant.git dentro de la imagen

      # Paso 2: Configurar Git (para hacer commit y push)
      - name: Configure Git
        run: | # Configura el usuario y el correo generico para actions en Git dentro del runner, es necesario cuando quieres hacer commits o push de cambios en un repositorio dentro del pipeline.
          git config --global user.name "GitHub Actions" 
          git config --global user.email "actions@github.com"  

      # Paso 3: Actualizar la imagen en el deployment, cambiando la referencia de la imagen para que use el último commit como tag.
      - name: Update Deployment Image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          sed -i "s|image:.*|image: image-registry.openshift-image-registry.svc:5000/technical-assistant/technical-assistant-git:$IMAGE_TAG|g" deployment-technical-assistant-git.yaml

      # Paso 4: Hacer commit y push de los cambios
      - name: Commit and Push Changes
        run: |
          git add deployment-technical-assistant-git.yaml
          git commit -m "Update image to latest version"
          git push origin main